### ISSUE TITLE
Missing coarse variable Temporal Causal 3D Teapot Dataset (CITRIS)

### ISSUE THREAD

**Issue by omar-s1** [phlippe/CITRIS#5]
Hi @phlippe,

Sorry, just one more thing to bring up. I can't seem to find the coarse variable version of the Temporal Causal 3D Teapot dataset for CITRIS. I'm using the dataset available here: https://zenodo.org/record/6637749#.Y4__6HbMI2x. I was wondering if you had the coarse variable version available somewhere too?

I tried to get around this by disabling this code https://github.com/phlippe/CITRIS/blob/main/experiments/datasets.py#L200-L201. Not sure if that's sufficient too.

Thanks,
Omar

**Comment by salemohamedo** [comment]
I think it was sufficient to disable the code as mentioned in my post, so closing this issue.
