### ISSUE TITLE
Code to create triplet dataset for temporal_causal3dident

### ISSUE THREAD

**Issue by Natithan** [phlippe/CITRIS#6]
Hi,

I would like to generate more triplet samples for the temporal_causal3dident data (besides test_triplets_coarse.npz that I can find in Zenodo, but I couldn't immediately find where the code for that was.
For the other datasets, I think it is the `create_triplet_dataset` function, but for temporal_causal3dident I can't find such a function.

Could you tell me where I can find this code? :)

**Comment by phlippe** [comment]
Hi, thanks for pointing that out! The code was indeed missing in the repo, I added it now [here](data_generation/temporal_causal3dident/triplet_generation_causal3dident.py). I didn't fully test it in this public repository (was running it in a different code base), but it should work here as well. Let me know if you run into any issues :)
