### ISSUE TITLE
Pong data generation - intervention probability

### ISSUE THREAD

**Issue by Natithan** [phlippe/CITRIS#7]
Hi!

I have a doubt regarding how to give settings for Pong data generation to match the paper results:
[The paper section C.2](https://arxiv.org/pdf/2202.03169.pdf#page=30) says 
![image](https://github.com/phlippe/CITRIS/assets/17345374/10f416ef-8905-40ac-a18a-295624069500).

In [data_generation_interventional_pong.py](https://github.com/phlippe/CITRIS/blob/main/data_generation/data_generation_interventional_pong.py#L206), this is implemented as:
```
if settings['single_target_interventions']:
        keys = sorted(list(intv_time_step.keys()))
        num_vars = len(keys)
        t = np.random.randint(num_vars)
        no_int_prob = (1 - settings['intv_prob']) ** num_vars
        if np.random.uniform() < no_int_prob:
            t = -1
        intv_targets = {key: int(t == i) for i, key in enumerate(keys)}
    else:
        intv_targets = {key: int(np.random.rand() < settings['intv_prob']) for key in intv_time_step}
```
Is it correct that, to match the paper results, I should set settings['intv_prob'] to such a value that `(1 - settings['intv_prob']) ** num_vars` = .35 (i.e., for `num_vars == 5`: `settings['intv_prob']` =~ .19, instead of [the default value of .15](https://github.com/phlippe/CITRIS/blob/main/data_generation/data_generation_interventional_pong.py#L241) which would give a chance of about 45% to not perform any intervention).

It's a detail, but I wasn't able to reproduce the good disentanglement on Pong so I'm trying to match the paper as close as possible :).

Thanks in advance!

**Comment by phlippe** [comment]
Hi, sorry for the confusion. I tried both settings back then (35% vs 45% no intv) and got similar results. For the paper, we reported the 35% results, but I apparently left the 45% in the code. You can try with 0.19 or change the above line to `no_int_prob = 1 - settings['intv_prob'] * num_vars` to get the 35% dataset version. :)

**Comment by Natithan** [comment]
Thanks!
